name: release
on: [ push ]
jobs:
  ranet-static:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: build
      strategy:
        matrix:
          target:
          - x86_64-unknown-linux-musl
          - aarch64-unknown-linux-musl
          - riscv64gc-unknown-linux-musl
      run: |
        cargo install cross --git https://github.com/cross-rs/cross
        cross build --release --features vendored --target ${{ matrix.target }}
