name: release
on: [ push ]
jobs:
  ranet-static:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
        - x86_64-unknown-linux-musl
        - aarch64-unknown-linux-musl
    steps:
    - uses: actions/checkout@v4
    - name: build
      run: |
        cargo install cross --git https://github.com/cross-rs/cross
        cross build --release --target ${{ matrix.target }}
    - uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.target }}
        path: target/${{ matrix.target }}/release/ranet
