name: release
on: [ push ]
jobs:
  ranet-static:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: build
      run: |
        apt-get install -y musl-tools

        rustup target add x86_64-unknown-linux-musl

        cargo install cargo-auditable
        cargo auditable build --release --features vendored --target x86_64-unknown-linux-musl
