name: release
on: workflow_dispatch
jobs:
  ranet-static:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: DeterminateSystems/nix-installer-action@main
    - run: |
        nix build -vL .#ranet-static
