name: release
on: [ push ]
jobs:
  ranet-static:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: build
      run: |
        cargo install cross --git https://github.com/cross-rs/cross

        cross build --release --target x86_64-unknown-linux-musl
        cross build --release --target aarch64-unknown-linux-musl
    - uses: actions/upload-artifact@v3
      with:
        name: binary
        path: target/x86_64-unknown-linux-musl/release/ranet
