name: release
on: [ push ]
jobs:
  ranet-static:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
        - x86_64-unknown-linux-musl
        - aarch64-unknown-linux-musl
    steps:
    - uses: actions/checkout@v3
    - name: build
      run: |
        cargo install cross --git https://github.com/cross-rs/cross
        cross build --release --features vendored --target ${{ matrix.target }}
